version: 2.1
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "66:eb:41:94:f3:6c:60:9c:29:0c:e6:14:61:12:f1:41"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
  test-unit:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8.0

    steps:
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            docker-php-ext-install zip
      - run:
          name: "Create Environment file"
          command: |
            cp .env.example .env
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Generate App key"
          command: php artisan key:generate
      # run tests with phpunit
      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit
#  test-feature:

workflows:
  test-push:
    jobs:
      - test-unit
#      - test-feature
#      - test-static
  deploy:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
